"""init

Revision ID: 0cb6d3e9b0b5
Revises: 
Create Date: 2026-06-02 07:15:09.743053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_init'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required Postgres extensions.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'premium', name='user_tier'), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('consent_record_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], name='users_consent_record_id_fkey', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('users_email_idx', 'users', ['email'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('guardian_name', sa.Text(), nullable=False),
    sa.Column('guardian_relation', sa.Text(), nullable=False),
    sa.Column('consent_text_sha256', sa.LargeBinary(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('consent_records_user_idx', 'consent_records', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('essay_text', sa.Text(), nullable=False),
    sa.Column('prompt_theme_title', sa.Text(), nullable=False),
    sa.Column('prompt_theme_context', sa.Text(), nullable=False),
    sa.Column('motivational_texts', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='correction_status'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('final_score', sa.SmallInteger(), nullable=True),
    sa.Column('c1_score', sa.SmallInteger(), nullable=True),
    sa.Column('c2_score', sa.SmallInteger(), nullable=True),
    sa.Column('c3_score', sa.SmallInteger(), nullable=True),
    sa.Column('c4_score', sa.SmallInteger(), nullable=True),
    sa.Column('c5_score', sa.SmallInteger(), nullable=True),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eliminatory_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('model_identifier', sa.Text(), nullable=True),
    sa.Column('output_schema_version', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message_pt_br', sa.Text(), nullable=True),
    sa.Column('quota_consumed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('parent_correction_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("status <> 'completed' OR (prompt_version IS NOT NULL AND model_identifier IS NOT NULL AND output_schema_version IS NOT NULL)", name='corrections_completed_has_provenance'),
    sa.CheckConstraint("status <> 'completed' OR final_score = c1_score + c2_score + c3_score + c4_score + c5_score", name='corrections_final_score_sum'),
    sa.CheckConstraint("status <> 'failed' OR error_code IS NOT NULL", name='corrections_failed_has_error'),
    sa.CheckConstraint('c1_score IS NULL OR c1_score IN (0, 40, 80, 120, 160, 200)', name='corrections_c1_score_scale'),
    sa.CheckConstraint('c2_score IS NULL OR c2_score IN (0, 40, 80, 120, 160, 200)', name='corrections_c2_score_scale'),
    sa.CheckConstraint('c3_score IS NULL OR c3_score IN (0, 40, 80, 120, 160, 200)', name='corrections_c3_score_scale'),
    sa.CheckConstraint('c4_score IS NULL OR c4_score IN (0, 40, 80, 120, 160, 200)', name='corrections_c4_score_scale'),
    sa.CheckConstraint('c5_score IS NULL OR c5_score IN (0, 40, 80, 120, 160, 200)', name='corrections_c5_score_scale'),
    sa.CheckConstraint('final_score IS NULL OR (final_score BETWEEN 0 AND 1000)', name='corrections_final_score_range'),
    sa.ForeignKeyConstraint(['parent_correction_id'], ['corrections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('corrections_parent_idx', 'corrections', ['parent_correction_id'], unique=False, postgresql_where=sa.text('parent_correction_id IS NOT NULL'))
    op.create_index('corrections_queue_idx', 'corrections', ['queued_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('corrections_user_listing_idx', 'corrections', ['user_id', 'queued_at'], unique=False, postgresql_using='btree', postgresql_ops={'queued_at': 'DESC'})
    op.create_index('corrections_user_queued_idx', 'corrections', ['user_id', 'queued_at'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('email_verification_tokens_user_idx', 'email_verification_tokens', ['user_id'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('refresh_tokens_user_active_idx', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('correction_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correction_id', sa.UUID(), nullable=False),
    sa.Column('input_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('event_type', sa.Enum('submitted', 'llm_started', 'llm_completed', 'schema_failed', 'retry', 'retry_exhausted', 'completed', 'failed', 'deleted', name='audit_event_type'), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('correction_audit_logs_correction_idx', 'correction_audit_logs', ['correction_id', 'created_at'], unique=False)
    op.create_table('grader_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('correction_id', sa.UUID(), nullable=False),
    sa.Column('pass_index', sa.SmallInteger(), nullable=False),
    sa.Column('c1_score', sa.SmallInteger(), nullable=False),
    sa.Column('c2_score', sa.SmallInteger(), nullable=False),
    sa.Column('c3_score', sa.SmallInteger(), nullable=False),
    sa.Column('c4_score', sa.SmallInteger(), nullable=False),
    sa.Column('c5_score', sa.SmallInteger(), nullable=False),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eliminatory_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('output_schema_version', sa.Text(), nullable=False),
    sa.Column('inference_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('c1_score IN (0, 40, 80, 120, 160, 200)', name='grader_passes_c1_scale'),
    sa.CheckConstraint('c2_score IN (0, 40, 80, 120, 160, 200)', name='grader_passes_c2_scale'),
    sa.CheckConstraint('c3_score IN (0, 40, 80, 120, 160, 200)', name='grader_passes_c3_scale'),
    sa.CheckConstraint('c4_score IN (0, 40, 80, 120, 160, 200)', name='grader_passes_c4_scale'),
    sa.CheckConstraint('c5_score IN (0, 40, 80, 120, 160, 200)', name='grader_passes_c5_scale'),
    sa.ForeignKeyConstraint(['correction_id'], ['corrections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correction_id', 'pass_index', name='grader_passes_correction_pass_uq')
    )
    op.create_index('grader_passes_correction_idx', 'grader_passes', ['correction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('grader_passes_correction_idx', table_name='grader_passes')
    op.drop_table('grader_passes')
    op.drop_index('correction_audit_logs_correction_idx', table_name='correction_audit_logs')
    op.drop_table('correction_audit_logs')
    op.drop_index('refresh_tokens_user_active_idx', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_index('email_verification_tokens_user_idx', table_name='email_verification_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('email_verification_tokens')
    op.drop_index('corrections_user_queued_idx', table_name='corrections')
    op.drop_index('corrections_user_listing_idx', table_name='corrections', postgresql_using='btree', postgresql_ops={'queued_at': 'DESC'})
    op.drop_index('corrections_queue_idx', table_name='corrections', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('corrections_parent_idx', table_name='corrections', postgresql_where=sa.text('parent_correction_id IS NOT NULL'))
    op.drop_table('corrections')
    op.drop_index('consent_records_user_idx', table_name='consent_records', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('consent_records')
    op.drop_index('users_email_idx', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
