import SwiftUI
import shared

/// Root SwiftUI view that hosts the Kotlin Multiplatform Compose UI.
///
/// The KMP shared module is built as an XCFramework by running:
///   ./gradlew :shared:assembleXCFramework
/// which produces `mobile/build/XCFrameworks/release/shared.xcframework`.
/// That framework must be added to the Xcode target's "Frameworks, Libraries,
/// and Embedded Content" section (Embed & Sign).
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)
    }
}

/// UIViewControllerRepresentable that bridges to MainViewController from KMP.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewController is generated by the Compose Multiplatform iOS entry point.
        // It is produced when the shared module includes a composeViewController in iosMain.
        // TODO: Replace with the actual MainViewController once iosMain entry is wired.
        return UIViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
